[package]
name = "lb"
version = "0.4.0"
authors = ["Szune <erikiwarson@gmail.com>"]
edition = "2018"
license = "AGPL-3.0-or-later"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
